apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "todo-listercise.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: {{ .Values.nodePorts.grafana }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    {{- include "todo-listercise.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsGroup: 472
      containers:
        - name: grafana
          image: {{ .Values.images.grafana }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_PATHS_CONFIG
              value: /etc/grafana/grafana.ini
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: GF_INSTALL_PLUGINS
              value: grafana-lokiexplore-app
          volumeMounts:
            - name: grafana-ini
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: data
              mountPath: /var/lib/grafana
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
      volumes:
        - name: grafana-ini
          configMap:
            name: grafana-ini
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards
          configMap:
            name: grafana-dashboards
        - name: data
          hostPath:
            path: {{ .Values.hostPath }}/grafana
            type: DirectoryOrCreate
