apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    {{- include "todo-listercise.labels" . | nindent 4 }}
spec:
  selector:
    app: tempo
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: http
      port: 3200
      targetPort: 3200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    {{- include "todo-listercise.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: tempo
          image: {{ .Values.images.tempo }}
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 3200
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: data
              mountPath: /var/tempo
          readinessProbe:
            httpGet:
              path: /ready
              port: 3200
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: data
          hostPath:
            path: {{ .Values.hostPath }}/tempo
            type: DirectoryOrCreate
